<?php

/**
 * @file
 * This module implements the integration between Content Type and RePEc.
 */

/**
 * Implements hook_node_insert().
 */
function repec_node_insert($node) {
  module_load_include('inc', 'repec', 'repec_aux');
  // This function generates the template file for the node.
  // This function is called in repec_aux
  repec_generate_paper_template($node);
}

/**
 * Implements hook_node_update().
 */
function repec_node_update($node) {
  module_load_include('inc', 'repec', 'repec_aux');
  // This function is called in repec_aux
  // It updates the template file for the node.
  repec_generate_paper_template($node);
}

/**
 * Implements hook_node_delete().
 */
function repec_node_delete($node) {
  module_load_include('inc', 'repec', 'repec_aux');
  // It's not automatically removed from RePEc repository.
  repec_remove_paper_template($node);
}

/**
 * Implements hook_menu().
 */
function repec_menu() {

  $items['admin/config/services/repec'] = array(
    'title' => 'RePEc',
    'description' => "Configure the integration with RePEc",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('repec_settings_form'),
    'file' => 'repec_form.inc',
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Implements hook_repec_paper_mapping().
 */
function repec_repec_paper_mapping($node) {
  // This function maps the series fields with the node fields to generate the template file.
  // The fields displayed on the settings page come from this function.
  // To display the fields on the settings page,
  // the field has to have the property 'visible' set to TRUE.
  $mapping = array();

  $node_vars = ($node == NULL) ? NULL : get_object_vars($node);
  $repec_series = variable_get('repec_series');
  $content_type = $repec_series['repec_paper']['content_type'];
  $series_name = $repec_series['name'];

  $mapping[] = array(
    'property' => 'Template-Type',
    'value' => 'ReDIF-Paper 1.0',
  );

  // Title of the Article.
  $mapping[] = array(
    'property' => 'Title',
    'value' => isset($node->title) ? $node->title : '',
  );

  $author_field = repec_get_field_content_type($content_type, $series_name, 'Author-Name');
  if (!empty($author_field) && !empty($node_vars[$author_field][LANGUAGE_NONE])) {
    $authors = repec_generate_array_authors($node_vars[$author_field][LANGUAGE_NONE]);

    foreach ($authors as $author) {
      $mapping[] = array(
        'property' => 'Author-Name',
        'value' => $author['value'],
        'visible' => TRUE,
      );
    }
  }
  else {
    $mapping[] = array(
      'property' => 'Author-Name',
      'value' => '',
      'visible' => TRUE,
    );
  }

  // Abstract of the article.
  $abstract = repec_get_field_content_type($content_type, $series_name, 'Abstract');
  if (!empty($abstract) && !empty($node_vars[$abstract][LANGUAGE_NONE][0]['value'])) {
    $mapping[] = array(
      'property' => 'Abstract',
      'value' => str_replace(array("\r", "\n", "<br />", "<br/>"), "", $node_vars[$abstract][LANGUAGE_NONE][0]['value']),
      'visible' => TRUE,
    );
  }
  else {
    $mapping[] = array(
      'property' => 'Abstract',
      'value' => '',
      'visible' => TRUE,
    );
  }

  // Date of the article.
  $create_date = repec_get_field_content_type($content_type, $series_name, 'Creation-Date');
  if (!empty($create_date) && !empty($node_vars[$create_date][LANGUAGE_NONE][0]['value'])) {
    $mapping[] = array(
      'property' => 'Creation-Date',
      'value' => strftime("%Y-%m-%d", strtotime($node_vars[$create_date][LANGUAGE_NONE][0]['value'])),
      'visible' => TRUE,
    );
  }
  else {
    $mapping[] = array(
      'property' => 'Creation-Date',
      'value' => '',
      'visible' => TRUE,
    );
  }

  // File for the article.
  $file_url = repec_get_field_content_type($content_type, $series_name, 'File-URL');
  if (!empty($file_url) && !empty($node_vars[$file_url][LANGUAGE_NONE][0]['fid'])) {
    $file_article = file_load($node_vars[$file_url][LANGUAGE_NONE][0]['fid']);

    $mapping[] = array(
      'property' => 'File-URL',
      'value' => str_replace(" ", "%20", file_create_url($file_article->uri)),
      'visible' => TRUE,
    );
    $mapping[] = array(
      'property' => 'File-Format',
      'value' => ucfirst($file_article->filemime),
    );
  }
  elseif (!empty($file_url) && !empty($node_vars[$file_url][LANGUAGE_NONE][0]['url'])) {
  $file_article = file_load($node_vars[$file_url][LANGUAGE_NONE][0]['url']);

  $mapping[] = array(
    'property' => 'File-URL',
    'value' => $node_vars[$file_url][LANGUAGE_NONE][0]['url'],
    'visible' => TRUE,
  );
  $mapping[] = array(
    'property' => 'File-Format',
    'value' => ucfirst($file_article->filemime),
  );
}
  else {
    $mapping[] = array(
      'property' => 'File-URL',
      'value' => '',
      'visible' => TRUE,
    );
  }

  // Keywords.
  $key = repec_get_field_content_type($content_type, $series_name, 'Keywords');
  if (!empty($key) && !empty($node_vars[$key][LANGUAGE_NONE])) {
    $keywords = '';
    foreach ($node_vars[$key][LANGUAGE_NONE] as $keyword) {
      $term = taxonomy_term_load($keyword['tid']);
      if ($term) {
        $keywords .= $term->name . ', ';
      }
    }
    if (strlen($keywords) > 0) {
      $keywords = substr($keywords, 0, strlen($keywords) - 2);
    }

    $mapping[] = array(
      'property' => 'Keywords',
      'value' => $keywords,
      'visible' => TRUE,
    );
  }
  else {
    $mapping[] = array(
      'property' => 'Keywords',
      'value' => '',
      'visible' => TRUE,
    );
  }

  // Article ID
  $article_id = repec_get_field_content_type($content_type, $series_name, 'Number');
  if (!empty($article_id) && !empty($node_vars[$article_id][LANGUAGE_NONE][0]['value'])) {
    $article_id = '';
    $mapping[] = array(
      'property' => 'Number',
      'value' => $node_vars[$article_id][LANGUAGE_NONE][0]['value'],
      'visible' => TRUE,
    );
    // Handle that uniquely identifies the paper.
    $mapping[] = array(
      'property' => 'Handle',
      'value' => 'RePEc:' . variable_get('repec_archive_code') . ":" . variable_get('repec_paper_dir', 'wpaper') . ":" . $node_vars[$article_id][LANGUAGE_NONE][0]['value'],
    );
  }
  else {
      // Number or id of the Article.
      $mapping[] = array(
        'property' => 'Number',
        'value' => '',
        'visible' => TRUE,
      );
      // Handle that uniquely identifies the paper.
      $mapping[] = array(
        'property' => 'Handle',
        'value' => 'RePEc:' . variable_get('repec_archive_code') . ":" . variable_get('repec_paper_dir', 'wpaper') . ":" . $node->nid,
      );
  }

  return $mapping;
}

/**
 * Implements hook_repec_series_mapping().
 */
function repec_repec_series_mapping() {
  // Default arrays.
  $provider = variable_get('repec_provider', array('name' => '', 'homepage' => '', 'institution' => ''));
  $maintainer = variable_get('repec_maintainer', array('name' => '', 'email' => ''));
  $repec_series = variable_get('repec_series');

  // It maps the series attributes to the settings informed
  // by the user to generate the series template file.
  // This runs when user saves the settings page.
  $attributes = array(
    array(
      'attribute' => 'Template-type',
      'value' => 'ReDIF-Series 1.0',
    ),
    array(
      'attribute' => 'Name',
      'value' => !empty($repec_series['repec_paper']['name']) ? $repec_series['repec_paper']['name'] : 'Working Paper',
    ),
    array(
      'attribute' => 'Provider-Name',
      'value' => $provider['name'],
    ),
    array(
      'attribute' => 'Provider-Homepage',
      'value' => $provider['homepage'],
    ),
    array(
      'attribute' => 'Provider-Institution',
      'value' => $provider['institution'],
    ),
    array(
      'attribute' => 'Maintainer-Name',
      'value' => $maintainer['name'],
    ),
    array(
      'attribute' => 'Maintainer-Email',
      'value' => $maintainer['email'],
    ),
    array(
      'attribute' => 'Type',
      'value' => 'ReDIF-Paper',
    ),
    array(
      'attribute' => 'Handle',
      'value' => 'RePEc:' . variable_get('repec_archive_code') . ':wpaper',
    ),
  );

  return $attributes;
}

/**
 * Implements hook_repec_archive_mapping().
 */
function repec_repec_archive_mapping() {
  // Default arrays.
  $provider = variable_get('repec_provider', array('name' => '', 'homepage' => '', 'institution' => ''));
  $maintainer = variable_get('repec_maintainer', array('name' => '', 'email' => ''));
  $repec_series = variable_get('repec_series');
  $repec_paper_name = !empty($series['repec_paper']['name']) ? $series['repec_paper']['name'] : 'Working Paper';

  // It maps the archive fields with the fields informed
  // by the user on the settings page.
  $attributes = array(
    array(
      'attribute' => 'Template-type',
      'value' => 'ReDIF-Archive 1.0',
    ),
    array(
      'attribute' => 'Handle',
      'value' => 'RePEc:' . variable_get('repec_archive_code'),
    ),
    array(
      'attribute' => 'Name',
      'value' => $provider['name'],
    ),
    array(
      'attribute' => 'Maintainer-Name',
      'value' => $maintainer['name'],
    ),
    array(
      'attribute' => 'Maintainer-Email',
      'value' => $maintainer['email'],
    ),
    array(
      'attribute' => 'Description',
      'value' => 'This archive collects ' .$repec_paper_name . ' from ' . $provider['name'],
    ),
    array(
      'attribute' => 'URL',
      'value' => $provider['homepage'] . variable_get('repec_base_path') . '/' . variable_get('repec_archive_code') . '/',
    ),
  );

  return $attributes;
}
